In [2]:
import sys
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [7]:
a[0],b[0]

(np.int64(1), np.int64(5))

In [8]:
a[0:]

array([1, 2, 3, 4])

In [10]:
a

array([1, 2, 3, 4])

In [11]:
b

array([5, 6, 7, 8])

In [9]:
a[0]

np.int64(1)

In [13]:
a[[0,2]]

array([1, 3])

In [14]:
a.dtype

dtype('int64')

In [15]:
c=np.array([0.1,0.2,0.3])

In [16]:
c.dtype

dtype('float64')

In [17]:
m=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [18]:
m.shape

(3, 3)

In [19]:
m.ndim

2

In [20]:
m.size

9

In [21]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
m[0][0]

np.int64(1)

In [23]:
m[0]

array([1, 2, 3])

In [24]:
m[0,0]

np.int64(1)

In [25]:
m[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
m[0:2,0:1]

array([[1],
       [4]])

In [32]:
m.sum()

np.int64(45)

In [33]:
m.mean()

np.float64(5.0)

In [34]:
m.std()

np.float64(2.581988897471611)

In [35]:
m.sum(axis=0)

array([12, 15, 18])

In [36]:
m.sum(axis=1)

array([ 6, 15, 24])

In [38]:
m >= 0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [40]:
e=np.array([1,2,3,4,5])

In [41]:
e[[True,False,True,False,True]]

array([1, 3, 5])

In [42]:
e >1

array([False,  True,  True,  True,  True])

In [44]:
e[e>3]

array([4, 5])

In [45]:
e.mean()

np.float64(3.0)

In [47]:
e[e>=e.mean()]

array([3, 4, 5])

In [49]:
e[~(e>=e.mean())]

array([1, 2])

In [50]:
m>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [51]:
m[m<2]

array([1])

In [52]:
m[m>2]

array([3, 4, 5, 6, 7, 8, 9])

In [53]:
m.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [55]:
m.dot(m)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [56]:
m.dot(m.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [67]:
np.ones([2,2],dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

In [68]:
np.zeros([10,10])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [71]:
f = np.ones([2,2])
f

array([[1., 1.],
       [1., 1.]])

In [72]:
print(f)

[[1. 1.]
 [1. 1.]]


In [74]:
f= f+f
f

array([[4., 4.],
       [4., 4.]])

In [77]:
np.ones([3,2],dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [82]:
x=np.arange(4,dtype=np.int8)
np.zeros_like(x)


array([0, 0, 0, 0], dtype=int8)

In [83]:
np.ones([5,5],dtype=np.int8)*5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]], dtype=int8)

In [90]:
X = np.array([[2,3], [6,2]], dtype=np.int8)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int8)